version: '3.10'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1

  db:
    image: python:3.10-slim
    command: sh -c "apt-get update && apt-get install -y sqlite3 && sqlite3 /data/db.sqlite3"
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data:
  static_volume:
  media_volume:
