# Generated by Django 5.1.5 on 2025-02-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="blog/", verbose_name="Изображение"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="comment/", verbose_name="Изображение"
            ),
        ),
    ]
