# Generated by Django 5.1.5 on 2025-02-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_blog_image_comment_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="material",
            field=models.CharField(
                default="Не указан", max_length=100, verbose_name="Название материала"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="material_composition",
            field=models.CharField(
                default="Не указан", max_length=100, verbose_name="Состав материала"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("lighting", "Освещение"), ("ceilings", "Потолки")],
                max_length=15,
                verbose_name="Категория",
            ),
        ),
    ]
