# Generated by Django 5.1.5 on 2025-03-13 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_category_options_category_category_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("lighting", "Освещение"),
                    ("ceilings", "Потолки"),
                    ("composition", "Состав материала:"),
                    ("material", "Материалы из:"),
                ],
                default="lighting",
                max_length=40,
                verbose_name="Тип категории",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="main.category",
                verbose_name="Подкатегория",
            ),
        ),
    ]
