# Generated by Django 5.1.5 on 2025-04-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_homepage_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone_number',
            field=models.CharField(max_length=18, verbose_name='Номер телефона'),
        ),
    ]
