# Generated by Django 5.1.5 on 2025-04-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_info_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='adress',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес'),
        ),
    ]
