# Generated by Django 5.1.5 on 2025-04-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_info_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='adress',
        ),
    ]
