# Generated by Django 5.1.5 on 2025-04-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_homepage_titile_homepage_titile_1_line_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='content_line_1',
            field=models.TextField(default='Текст первый', verbose_name='Текст первый'),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_line_2',
            field=models.TextField(default='Текст второй', verbose_name='Текст второй'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_line_1',
            field=models.ImageField(blank=True, upload_to='blog/', verbose_name='Изображение 1'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_line_2',
            field=models.ImageField(blank=True, upload_to='blog/', verbose_name='Изображение 2'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=24, verbose_name='Описание'),
        ),
    ]
